version: "3"
services:
  backend:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src
    working_dir: /go/src
    command: go run main.go
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 25s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
volumes:
  postgres_data:
